title: Robotics Conference Deadlines
description: Countdowns to Robotics conference deadlines
author: Abhishek Das

domain: ""
baseurl: "/robo-deadlines"

github_username: danieledema
github_repo: robo-deadlines

markdown: kramdown
ga_id: UA-36274081-2

include: ['_pages']
